data:
  id: data_3
  params:
    balanced_data: false
    cnv_levels: 3
    combine_type: union
    data_type:
    - mut_important
    - cnv_del
    - cnv_amp
    - promoter
    drop_AR: false
    mut_binary: true
    selected_genes: breast_expressed_genes.csv
    training_split: '3'
    use_coding_genes_only: true
  type: prostate_paper
models:
  id: dense_data_3
  params:
    build_fn: !!python/name:model.builders.prostate_models.build_dense ''
    fitting_params:
      batch_size: 32
      class_weight: auto
      debug: false
      early_stop: false
      epoch: 5
      monitor: val_f1
      n_outputs: 1
      prediction_output: average
      reduce_lr: false
      reduce_lr_after_nepochs:
        drop: 0.25
        epochs_drop: 50
      samples_per_epoch: 10
      save_gradient: false
      save_name: dense
      select_best_model: false
      shuffle: true
      verbose: 2
    model_params:
      activation: selu
      data_params:
        id: ALL
        params:
          balanced_data: false
          cnv_levels: 3
          combine_type: union
          data_type:
          - mut_important
          - cnv_del
          - cnv_amp
          - promoter
          drop_AR: false
          mut_binary: true
          selected_genes: breast_expressed_genes.csv
          training_split: 0
          use_coding_genes_only: true
        type: prostate_paper
      n_weights: 71009
      optimizer: Adam
      w_reg: 0.01
  type: nn
pipeline:
  params:
    n_splits: 5
    save_train: true
  type: crossvalidation
pre:
  type: null
scores: '{"accuracy":{"0":0.6967213115,"1":0.737704918,"2":0.7295081967,"3":0.6967213115,"4":0.6721311475},"auc":{"0":0.8072874494,"1":0.8245614035,"2":0.8005398111,"3":0.7800269906,"4":0.7905533063},"aupr":{"0":0.8149107783,"1":0.8534364034,"2":0.8301549511,"3":0.8100716994,"4":0.8447971115},"f1":{"0":0.6605504587,"1":0.737704918,"2":0.7226890756,"3":0.7299270073,"4":0.5744680851},"precision":{"0":0.8181818182,"1":0.7894736842,"2":0.7962962963,"3":0.6944444444,"4":0.9310344828},"recall":{"0":0.5538461538,"1":0.6923076923,"2":0.6615384615,"3":0.7692307692,"4":0.4153846154}}'
scores_mean: '{"accuracy":0.706557377,"auc":0.8005937922,"aupr":0.8306741887,"f1":0.685067909,"precision":0.8058861452,"recall":0.6184615385}'
scores_std: '{"accuracy":0.0268121758,"auc":0.0169045781,"aupr":0.0186466663,"f1":0.0689778443,"precision":0.0845486202,"recall":0.1373459331}'
