data:
  id: data_9
  params:
    balanced_data: false
    cnv_levels: 3
    combine_type: union
    data_type:
    - mut_important
    - cnv_del
    - cnv_amp
    - promoter
    drop_AR: false
    mut_binary: true
    selected_genes: breast_expressed_genes.csv
    training_split: '9'
    use_coding_genes_only: true
  type: prostate_paper
models:
  id: dense_data_9
  params:
    build_fn: !!python/name:model.builders.prostate_models.build_dense ''
    fitting_params:
      batch_size: 32
      class_weight: auto
      debug: false
      early_stop: false
      epoch: 5
      monitor: val_f1
      n_outputs: 1
      prediction_output: average
      reduce_lr: false
      reduce_lr_after_nepochs:
        drop: 0.25
        epochs_drop: 50
      samples_per_epoch: 10
      save_gradient: false
      save_name: dense
      select_best_model: false
      shuffle: true
      verbose: 2
    model_params:
      activation: selu
      data_params:
        id: ALL
        params:
          balanced_data: false
          cnv_levels: 3
          combine_type: union
          data_type:
          - mut_important
          - cnv_del
          - cnv_amp
          - promoter
          drop_AR: false
          mut_binary: true
          selected_genes: breast_expressed_genes.csv
          training_split: 0
          use_coding_genes_only: true
        type: prostate_paper
      n_weights: 71009
      optimizer: Adam
      w_reg: 0.01
  type: nn
pipeline:
  params:
    n_splits: 5
    save_train: true
  type: crossvalidation
pre:
  type: null
scores: '{"accuracy":{"0":0.762295082,"1":0.6967213115,"2":0.7131147541,"3":0.737704918,"4":0.6967213115},"auc":{"0":0.84048583,"1":0.8067476383,"2":0.7956815115,"3":0.8118758435,"4":0.8056680162},"aupr":{"0":0.8574808927,"1":0.8452981629,"2":0.8376480378,"3":0.8354192908,"4":0.8339437981},"f1":{"0":0.756302521,"1":0.640776699,"2":0.6846846847,"3":0.7288135593,"4":0.6605504587},"precision":{"0":0.8333333333,"1":0.8684210526,"2":0.8260869565,"3":0.8113207547,"4":0.8181818182},"recall":{"0":0.6923076923,"1":0.5076923077,"2":0.5846153846,"3":0.6615384615,"4":0.5538461538}}'
scores_mean: '{"accuracy":0.7213114754,"auc":0.8120917679,"aupr":0.8419580365,"f1":0.6942255846,"precision":0.8314687831,"recall":0.6}'
scores_std: '{"accuracy":0.0283942755,"auc":0.016921807,"aupr":0.0097169287,"f1":0.0477799651,"precision":0.0222508276,"recall":0.0761499611}'
