data:
  id: data_6
  params:
    balanced_data: false
    cnv_levels: 3
    combine_type: union
    data_type:
    - mut_important
    - cnv_del
    - cnv_amp
    - promoter
    drop_AR: false
    mut_binary: true
    selected_genes: breast_expressed_genes.csv
    training_split: '6'
    use_coding_genes_only: true
  type: prostate_paper
models:
  id: dense_data_6
  params:
    build_fn: !!python/name:model.builders.prostate_models.build_dense ''
    fitting_params:
      batch_size: 32
      class_weight: auto
      debug: false
      early_stop: false
      epoch: 5
      monitor: val_f1
      n_outputs: 1
      prediction_output: average
      reduce_lr: false
      reduce_lr_after_nepochs:
        drop: 0.25
        epochs_drop: 50
      samples_per_epoch: 10
      save_gradient: false
      save_name: dense
      select_best_model: false
      shuffle: true
      verbose: 2
    model_params:
      activation: selu
      data_params:
        id: ALL
        params:
          balanced_data: false
          cnv_levels: 3
          combine_type: union
          data_type:
          - mut_important
          - cnv_del
          - cnv_amp
          - promoter
          drop_AR: false
          mut_binary: true
          selected_genes: breast_expressed_genes.csv
          training_split: 0
          use_coding_genes_only: true
        type: prostate_paper
      n_weights: 71009
      optimizer: Adam
      w_reg: 0.01
  type: nn
pipeline:
  params:
    n_splits: 5
    save_train: true
  type: crossvalidation
pre:
  type: null
scores: '{"accuracy":{"0":0.7131147541,"1":0.737704918,"2":0.737704918,"3":0.7213114754,"4":0.7540983607},"auc":{"0":0.8094466937,"1":0.8291497976,"2":0.816194332,"3":0.7746288799,"4":0.7983805668},"aupr":{"0":0.8397363025,"1":0.866360457,"2":0.8530342784,"3":0.8179684962,"4":0.8162939012},"f1":{"0":0.6846846847,"1":0.7538461538,"2":0.724137931,"3":0.7462686567,"4":0.75},"precision":{"0":0.8260869565,"1":0.7538461538,"2":0.8235294118,"3":0.7246376812,"4":0.8181818182},"recall":{"0":0.5846153846,"1":0.7538461538,"2":0.6461538462,"3":0.7692307692,"4":0.6923076923}}'
scores_mean: '{"accuracy":0.7327868852,"auc":0.805560054,"aupr":0.838678687,"f1":0.7317874853,"precision":0.7892564043,"recall":0.6892307692}'
scores_std: '{"accuracy":0.0159783514,"auc":0.0205727514,"aupr":0.0218144023,"f1":0.028745323,"precision":0.0468968906,"recall":0.0764601455}'
