data:
  id: data_12
  params:
    balanced_data: false
    cnv_levels: 3
    combine_type: union
    data_type:
    - mut_important
    - cnv_del
    - cnv_amp
    - promoter
    drop_AR: false
    mut_binary: true
    selected_genes: breast_expressed_genes.csv
    training_split: '12'
    use_coding_genes_only: true
  type: prostate_paper
models:
  id: P-net_data_12
  params:
    build_fn: !!python/name:model.builders.prostate_models.build_pnet2 ''
    feature_importance: deepexplain_grad*input
    fitting_params:
      batch_size: 32
      class_weight: auto
      debug: false
      early_stop: false
      epoch: 5
      lr: 0.008
      max_f1: true
      monitor: val_o6_f1
      n_outputs: 3
      prediction_output: average
      reduce_lr: false
      reduce_lr_after_nepochs:
        drop: 0.25
        epochs_drop: 50
      samples_per_epoch: 10
      save_gradient: false
      save_name: pnet
      select_best_model: false
      shuffle: true
      verbose: 2
    model_params:
      activation: tanh
      add_unk_genes: false
      attention: false
      data_params:
        id: ALL
        params:
          balanced_data: false
          cnv_levels: 3
          combine_type: union
          data_type:
          - mut_important
          - cnv_del
          - cnv_amp
          - promoter
          drop_AR: false
          mut_binary: true
          selected_genes: breast_expressed_genes.csv
          training_split: 18
          use_coding_genes_only: true
        type: prostate_paper
      dropout:
      - 0.5
      - 0.1
      - 0.1
      - 0.1
      dropout_testing: false
      kernel_initializer: lecun_uniform
      loss_weights:
      - 2
      - 20
      - 400
      n_hidden_layers: 2
      optimizer: Adam
      shuffle_genes: false
      use_bias: true
      w_reg:
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      w_reg_outcomes:
      - 0.01
      - 0.01
      - 0.01
  type: nn
pipeline:
  params:
    n_splits: 5
    save_train: true
  type: crossvalidation
pre:
  type: null
scores: '{"accuracy":{"0":0.7131147541,"1":0.762295082,"2":0.762295082,"3":0.7704918033,"4":0.7704918033},"auc":{"0":0.8126855601,"1":0.8197031039,"2":0.8321187584,"3":0.8388663968,"4":0.8412955466},"aupr":{"0":0.8593458881,"1":0.864179065,"2":0.8723995298,"3":0.8806545505,"4":0.8727191634},"f1":{"0":0.6666666667,"1":0.7387387387,"2":0.756302521,"3":0.7543859649,"4":0.7846153846},"precision":{"0":0.875,"1":0.8913043478,"2":0.8333333333,"3":0.8775510204,"4":0.7846153846},"recall":{"0":0.5384615385,"1":0.6307692308,"2":0.6923076923,"3":0.6615384615,"4":0.7846153846}}'
scores_mean: '{"accuracy":0.7557377049,"auc":0.8289338731,"aupr":0.8698596394,"f1":0.7401418552,"precision":0.8523608172,"recall":0.6615384615}'
scores_std: '{"accuracy":0.0241768544,"auc":0.0123574296,"aupr":0.0082759579,"f1":0.0442790263,"precision":0.0436324601,"recall":0.0897069522}'
