data:
  id: data_9
  params:
    balanced_data: false
    cnv_levels: 3
    combine_type: union
    data_type:
    - mut_important
    - cnv_del
    - cnv_amp
    - promoter
    drop_AR: false
    mut_binary: true
    selected_genes: breast_expressed_genes.csv
    training_split: '9'
    use_coding_genes_only: true
  type: prostate_paper
models:
  id: P-net_data_9
  params:
    build_fn: !!python/name:model.builders.prostate_models.build_pnet2 ''
    feature_importance: deepexplain_grad*input
    fitting_params:
      batch_size: 32
      class_weight: auto
      debug: false
      early_stop: false
      epoch: 5
      lr: 0.008
      max_f1: true
      monitor: val_o6_f1
      n_outputs: 3
      prediction_output: average
      reduce_lr: false
      reduce_lr_after_nepochs:
        drop: 0.25
        epochs_drop: 50
      samples_per_epoch: 10
      save_gradient: false
      save_name: pnet
      select_best_model: false
      shuffle: true
      verbose: 2
    model_params:
      activation: tanh
      add_unk_genes: false
      attention: false
      data_params:
        id: ALL
        params:
          balanced_data: false
          cnv_levels: 3
          combine_type: union
          data_type:
          - mut_important
          - cnv_del
          - cnv_amp
          - promoter
          drop_AR: false
          mut_binary: true
          selected_genes: breast_expressed_genes.csv
          training_split: 18
          use_coding_genes_only: true
        type: prostate_paper
      dropout:
      - 0.5
      - 0.1
      - 0.1
      - 0.1
      dropout_testing: false
      kernel_initializer: lecun_uniform
      loss_weights:
      - 2
      - 20
      - 400
      n_hidden_layers: 2
      optimizer: Adam
      shuffle_genes: false
      use_bias: true
      w_reg:
      - 0.001
      - 0.001
      - 0.001
      - 0.001
      w_reg_outcomes:
      - 0.01
      - 0.01
      - 0.01
  type: nn
pipeline:
  params:
    n_splits: 5
    save_train: true
  type: crossvalidation
pre:
  type: null
scores: '{"accuracy":{"0":0.7704918033,"1":0.7786885246,"2":0.7540983607,"3":0.7786885246,"4":0.737704918},"auc":{"0":0.8229419703,"1":0.8353576248,"2":0.828340081,"3":0.8294197031,"4":0.8340080972},"aupr":{"0":0.8690556576,"1":0.8784092609,"2":0.8768944748,"3":0.8668243422,"4":0.8719390159},"f1":{"0":0.7586206897,"1":0.7906976744,"2":0.7457627119,"3":0.7567567568,"4":0.768115942},"precision":{"0":0.862745098,"1":0.796875,"2":0.8301886792,"3":0.9130434783,"4":0.7260273973},"recall":{"0":0.6769230769,"1":0.7846153846,"2":0.6769230769,"3":0.6461538462,"4":0.8153846154}}'
scores_mean: '{"accuracy":0.7639344262,"auc":0.8300134953,"aupr":0.8726245503,"f1":0.7639907549,"precision":0.8257759306,"recall":0.72}'
scores_std: '{"accuracy":0.0177700684,"auc":0.0049415568,"aupr":0.0049634791,"f1":0.0169093658,"precision":0.0703328697,"recall":0.0748963781}'
