data_params:
  id: data_0
  params:
    balanced_data: false
    cnv_levels: 3
    combine_type: union
    data_type:
    - mut_important
    - cnv_del
    - cnv_amp
    drop_AR: false
    mut_binary: true
    selected_genes: tcga_prostate_expressed_genes_and_cancer_genes.csv
    training_split: '0'
    use_coding_genes_only: true
  type: prostate_paper
exp_name: /home/user/tfprojects/pnet_prostate_paper-master2_backup/_logs/p1000/./compare/onsplit_ML_test
features_params: {}
model_params:
  id: Adaptive Boosting_data_0
  params:
    learning_rate: 0.1
    n_estimators: 50
  type: adaboost
pipeline_params:
  params:
    eval_dataset: test
    save_train: true
  type: one_split
pre_params:
  type: null
score: '{''aupr'': 0.7486098113815948, ''f1'': 0.7, ''auc'': 0.7924787606196901, ''recall'':
  0.6086956521739131, ''precision'': 0.8235294117647058, ''accuracy'': 0.7318435754189944}'
task: classification_binary
